name: Ejecutar archivos en paralelo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dar permisos al script
        run: chmod +x scripts/ejecutar.sh

      - name: Ejecutar Bash
        run: ./scripts/ejecutar.sh
        
      - name: Guardar archivos en el repositorio
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add Hola1.txt Hola2.txt

          git commit -m "Crear Hola1 y Hola2 desde GitHub Actions" || echo "No hay cambios para commitear"

          git push